easy_admin:
  design:
    menu:
      - label: 'Entities'
        children:
        - { label: 'Categories', entity: 'Category'}
        - { label: 'Posts', entity: 'Post'}
      - label: 'Security'
        children:
        - { label: 'Users', entity: 'User'}
  entities:
    User:
      class: App\Entity\User
      form:
        fields:
          - property: 'roles'
            type: 'choice'
            type_options:
              expanded: true
              choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' }
              multiple: true
          - 'fullName'
          - 'username'
          - 'email'
    # List the entity class name you want to manage
    Post:
      class: App\Entity\Post
      form:
        fields: ['name', 'content', 'enable', 'category', { property: 'imageFile', type: 'vich_image' }]
      list:
        fields:
          - 'name'
          - 'enable'
          - 'category'
          - { property: 'image', type: 'image', base_path: '%app.path.post_images%' }
      show:
        fields:
          - 'name'
          - 'content'
          - 'enable'
          - 'category'
          - { property: 'image', type: 'image', base_path: '%app.path.post_images%' }
    Category:
      class: App\Entity\Category
      form:
        fields: ['name','slug','enable','posts']